import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import config from '../config';

const AuthService = {
    /** Test */
    secret: config.JWT_SECRET,
    /**
     * 
     * @param {string} password - The password string given by user
     * @param {string} hash - The hash generated by bcrypt and stored in db
     * @returns Returns promise that resolves to bool wether password is found or not.
     */
    comparePasswords(password, hash) {
        return bcrypt.compare(password, hash);
    },
    createJWT(subject, payload) {
        return jwt.sign(payload, this.secret, {
            subject,
            algorithm: 'HS256',
        });
    },
    verifyJwt(token) {
        return jwt.verify(token, config.JWT_SECRET, {
            algorithms: ['HS256'],
        });
    },
}

export default AuthService;